/* Excercises from Chapter 6 Learning SQL Alan Beaulieu*/
use learning_sql;
/*6.1 If set A={LMNOP} and set B={PQRST}, what sets are generated by the following operations?
1 A union B
2 A union all B
3 A intersect B
4 A except B*/
/*A:
1.- {LMNOPQRST}
2.-{LMNOPPQRST}
3.- {P}
4.-{LMNO}
*/
/*6.2 Write a compound query that finds the first and last names of all individual customers along with the first and last names of all employees*/
select fname, lname from individual union all select fname, lname from employee;
/*6.3 Sort the result from excersice 6-2 by the lname column*/
select fname, lname from individual union all select fname, lname from employee order by lname;
 